{% set name = "sseclient-py" %}
{% set version = "1.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # No pypi package available yet for version 1.9.0, so use github source.
  - url: https://github.com/mpetazzoni/sseclient/archive/refs/tags/{{ name }}-{{ version }}.tar.gz
    sha256: 467b6abcc5833e17195c0be6a18f599cb2a3a784f5ec16d539e5d1d6273d3745

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - hatchling
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - sseclient
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests

about:
  home: https://github.com/mpetazzoni/sseclient
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python client for SSE event sources that seamlessly integrates with urllib3 and requests.
  description: A Python client for SSE event sources that seamlessly integrates with urllib3 and requests.
  dev_url: https://github.com/mpetazzoni/sseclient
  doc_url: https://github.com/mpetazzoni/sseclient/blob/master/README.rst